export const Images = {
  Left_Arrow: require('../images/right_arrow.png'),
  Right_Arrow: require('../images/left_arrow.png'),
  Question: require('../images/question.png'),
  Down_Arrow: require('../images/down_arrow.png'),
  Plus_Arrow: require('../images/plus.png'),
  Info_Icon: require('../images/info.png'),
  Image_Icon: require('../images/image.png'),
  Dot_Icon: require('../images/black_circle.png'),
  Sad_Icon: require('../images/sad.png'),
  Happy_Icon: require('../images/happy.png'),
  LogoBlack: require('../images/logo_black.jpg'),
  LogoWhite: require('../images/logo_white.png'),
  Close_Icon: require('../images/close.png'),
  Location_Icon: require('../images/location.png'),
  left_Icon: require('../images/right.png'),
  right_Icon: require('../images/left.png'),
  share: require('../images/share.png'),
  profile: require('../images/profile.png'),
  agreement: require('../images/agreement.png'),
  star: require('../images/star.png'),
};
